services:
  - type: web
    name: tien-len
    runtime: node
    buildCommand: cd server && npm install && cd ../client && npm install --include=dev && npm run build
    startCommand: cd server && node index.js
    maxShutdownDelaySeconds: 300
    envVars:
      - key: NODE_ENV
        value: production
