export default [
  { id: 'chat', label: 'Chop', anim: true, set: 'core', meme: 'Chặt heo, chopping the 2s' },
  { id: 'thoi', label: 'Stuck with a 2', anim: true, set: 'core', meme: 'Thối heo, stuck holding a 2' },
  { id: 'toitrang', label: 'Instant win', anim: true, set: 'core', meme: 'Tới trắng, an instant win' },
  { id: 'cong', label: 'Frozen out', anim: true, set: 'core', meme: 'Cóng, never got to play' },
  { id: 'gg', label: 'GG', anim: false, set: 'core', meme: 'GG fist bump' },
  { id: 'ez', label: 'EZ', anim: true, set: 'core', meme: 'Deal With It, EZ' },
  { id: 'icant', label: 'Crying laughing', anim: true, set: 'core', meme: 'ICANT, skull crying laughing' },
  { id: 'clown', label: 'Clown', anim: false, set: 'core', meme: 'Clown moment' },
  { id: 'sweat', label: 'Nervous', anim: true, set: 'core', meme: 'monkaS, one card left' },
  { id: 'flip', label: 'Table flip', anim: true, set: 'core', meme: 'Table flip' },
  { id: 'sleep', label: 'Sleepy', anim: true, set: 'core', meme: 'Bedge, waiting on a slow player' },
  { id: 'stonks', label: 'Stonks', anim: false, set: 'core', meme: 'Stonks' },
  { id: 'tw-67', label: '6 7', anim: true, set: 'twitch', meme: '67, the 67 kid' },
  { id: 'tw-scuba', label: 'Scuba cat', anim: true, set: 'twitch', meme: 'Scuba cat dance' },
  { id: 'tw-aura', label: '+1000 aura', anim: true, set: 'twitch', meme: 'Aura farming' },
  { id: 'tw-banana', label: 'Banana cat', anim: true, set: 'twitch', meme: 'Banana cat' },
  { id: 'tw-huh', label: 'HUH', anim: true, set: 'twitch', meme: 'HUH cat' },
  { id: 'tw-spin', label: 'Spinning cat', anim: true, set: 'twitch', meme: 'OIIA spinning cat' },
  { id: 'tw-vibe', label: 'Vibing cat', anim: true, set: 'twitch', meme: 'Bongo cat, catJAM' },
  { id: 'tw-sadge', label: 'Sadge', anim: true, set: 'twitch', meme: 'Sadge' },
  { id: 'tw-pray', label: 'Pray', anim: true, set: 'twitch', meme: 'Prayge' },
  { id: 'tw-modcheck', label: 'modCheck', anim: true, set: 'twitch', meme: 'modCheck' },
  { id: 'tw-clap', label: 'Clap', anim: true, set: 'twitch', meme: 'Clap, peepoClap' },
  { id: 'tw-cooked', label: 'Cooked', anim: true, set: 'twitch', meme: 'Chat, we are cooked' },
  { id: 'tw-copium', label: 'Copium', anim: false, set: 'twitch', meme: 'Copium' },
  { id: 'tw-deal', label: 'Deal with it', anim: true, set: 'twitch', meme: 'Deal With It doge' },
  { id: 'tw-hi', label: 'Doge hi', anim: false, set: 'twitch', meme: 'Doge' },
  { id: 'tw-lul', label: 'Skull', anim: false, set: 'twitch', meme: 'Skull, I am dead' },
  { id: 'tw-pog', label: 'Pog', anim: false, set: 'twitch', meme: 'PogChamp, Komodo Hype' },
  { id: 'tw-f', label: 'Press F', anim: false, set: 'twitch', meme: 'Press F to pay respects' },
  { id: 'tw-rat', label: 'Sus rat', anim: false, set: 'twitch', meme: 'Sus rat' },
  { id: 'tw-ratjam', label: 'Rat jam', anim: true, set: 'twitch', meme: 'ratJAM' },
  { id: 'tw-potato', label: 'Ski potato', anim: true, set: 'twitch', meme: 'Baked potato with ski goggles' },
  { id: 'tw-sahur', label: 'Tung tung sahur', anim: true, set: 'twitch', meme: 'Tung Tung Tung Sahur' },
  { id: 'tw-shark', label: 'Tralalero', anim: true, set: 'twitch', meme: 'Tralalero Tralala' },
  { id: 'tw-croc', label: 'Bombardiro', anim: true, set: 'twitch', meme: 'Bombardiro Crocodilo' },
  { id: 'tw-cappuccina', label: 'Cappuccina', anim: true, set: 'twitch', meme: 'Ballerina Cappuccina' },
];
