export default [
  { id: 'chat', label: 'Chop', anim: true, set: 'core', meme: 'Chặt heo, chopping the 2s' },
  { id: 'thoi', label: 'Stuck with a 2', anim: true, set: 'core', meme: 'Thối heo, stuck holding a 2' },
  { id: 'toitrang', label: 'Instant win', anim: true, set: 'core', meme: 'Tới trắng, an instant win' },
  { id: 'cong', label: 'Frozen out', anim: true, set: 'core', meme: 'Cóng, never got to play' },
  { id: 'gg', label: 'GG', anim: false, set: 'core', meme: 'GG fist bump' },
  { id: 'ez', label: 'EZ', anim: true, set: 'core', meme: 'Deal With It, EZ' },
  { id: 'icant', label: 'Crying laughing', anim: true, set: 'core', meme: 'ICANT, skull crying laughing' },
  { id: 'clown', label: 'Clown', anim: false, set: 'core', meme: 'Clown moment' },
  { id: 'sweat', label: 'Nervous', anim: true, set: 'core', meme: 'monkaS, one card left' },
  { id: 'flip', label: 'Table flip', anim: true, set: 'core', meme: 'Table flip' },
  { id: 'sleep', label: 'Sleepy', anim: true, set: 'core', meme: 'Bedge, waiting on a slow player' },
  { id: 'stonks', label: 'Stonks', anim: false, set: 'core', meme: 'Stonks' },
  { id: 'tw-67', label: '6 7', anim: true, set: 'twitch', meme: '67, the 67 kid' },
  { id: 'tw-scuba', label: 'Scuba cat', anim: true, set: 'twitch', meme: 'Scuba cat dance' },
  { id: 'tw-aura', label: '+1000 aura', anim: true, set: 'twitch', meme: 'Aura farming' },
  { id: 'tw-banana', label: 'Banana cat', anim: true, set: 'twitch', meme: 'Banana cat' },
  { id: 'tw-huh', label: 'HUH', anim: true, set: 'twitch', meme: 'HUH cat' },
  { id: 'tw-spin', label: 'Spinning cat', anim: true, set: 'twitch', meme: 'OIIA spinning cat' },
  { id: 'tw-vibe', label: 'Vibing cat', anim: true, set: 'twitch', meme: 'Bongo cat, catJAM' },
  { id: 'tw-sadge', label: 'Sadge', anim: true, set: 'twitch', meme: 'Sadge' },
  { id: 'tw-pray', label: 'Pray', anim: true, set: 'twitch', meme: 'Prayge' },
  { id: 'tw-modcheck', label: 'modCheck', anim: true, set: 'twitch', meme: 'modCheck' },
  { id: 'tw-clap', label: 'Clap', anim: true, set: 'twitch', meme: 'Clap, peepoClap' },
  { id: 'tw-cooked', label: 'Cooked', anim: true, set: 'twitch', meme: 'Chat, we are cooked' },
  { id: 'tw-copium', label: 'Copium', anim: false, set: 'twitch', meme: 'Copium' },
  { id: 'tw-deal', label: 'Deal with it', anim: true, set: 'twitch', meme: 'Deal With It doge' },
  { id: 'tw-hi', label: 'Doge hi', anim: false, set: 'twitch', meme: 'Doge' },
  { id: 'tw-lul', label: 'Skull', anim: false, set: 'twitch', meme: 'Skull, I am dead' },
  { id: 'tw-pog', label: 'Pog', anim: false, set: 'twitch', meme: 'PogChamp, Komodo Hype' },
  { id: 'tw-f', label: 'Press F', anim: false, set: 'twitch', meme: 'Press F to pay respects' },
  { id: 'tw-rat', label: 'Sus rat', anim: false, set: 'twitch', meme: 'Sus rat' },
  { id: 'tw-ratjam', label: 'Rat jam', anim: true, set: 'twitch', meme: 'ratJAM' },
  { id: 'tw-potato', label: 'Ski potato', anim: true, set: 'twitch', meme: 'Baked potato with ski goggles' },
  { id: 'tw-sahur', label: 'Tung tung sahur', anim: true, set: 'twitch', meme: 'Tung Tung Tung Sahur' },
  { id: 'tw-shark', label: 'Tralalero', anim: true, set: 'twitch', meme: 'Tralalero Tralala' },
  { id: 'tw-croc', label: 'Bombardiro', anim: true, set: 'twitch', meme: 'Bombardiro Crocodilo' },
  { id: 'tw-cappuccina', label: 'Cappuccina', anim: true, set: 'twitch', meme: 'Ballerina Cappuccina' },
  { id: 'smug-fox', label: 'Smug fox', anim: true, set: 'extra', meme: 'Smug fox smirk, Nick Wilde energy from Zootopia' },
  { id: 'no-u', label: 'No u', anim: true, set: 'extra', meme: 'No U, the reverse card' },
  { id: 'all-in', label: 'All in', anim: true, set: 'extra', meme: 'Going all in' },
  { id: 'ace-sleeve', label: 'Ace up sleeve', anim: true, set: 'extra', meme: 'Ace up the sleeve, cheating' },
  { id: 'peek', label: 'Peek', anim: true, set: 'extra', meme: 'Poker face, peeking over the cards' },
  { id: 'bait', label: 'Bait', anim: false, set: 'extra', meme: 'Baited, Jebaited' },
  { id: 'waiting', label: 'Waiting', anim: true, set: 'extra', meme: 'Skeleton still waiting for their turn' },
  { id: 'make-it-rain', label: 'Make it rain', anim: true, set: 'extra', meme: 'Make it rain, throwing money' },
  { id: 'big-w', label: 'W', anim: false, set: 'extra', meme: 'W in the chat' },
  { id: 'big-l', label: 'L', anim: false, set: 'extra', meme: 'Taking an L' },
  { id: 'this-is-fine', label: 'This is fine', anim: true, set: 'extra', meme: 'This Is Fine, calm in a burning room' },
  { id: 'facepalm', label: 'Facepalm', anim: false, set: 'extra', meme: 'Facepalm' },
  { id: 'thinking', label: 'Thinking', anim: false, set: 'extra', meme: 'Thinking face, hmm' },
  { id: 'big-brain', label: 'Big brain', anim: true, set: 'extra', meme: 'Galaxy brain, big brain time' },
  { id: 'side-eye', label: 'Side eye', anim: true, set: 'extra', meme: 'Monkey puppet side eye, awkward look away' },
  { id: 'popcorn', label: 'Popcorn', anim: true, set: 'extra', meme: 'Grabbing popcorn for the drama' },
  { id: 'mic-drop', label: 'Mic drop', anim: true, set: 'extra', meme: 'Mic drop' },
  { id: 'sip-tea', label: 'Sip tea', anim: true, set: 'extra', meme: 'Sipping tea, none of my business' },
  { id: 'crying-thumbs', label: 'Sad thumbs up', anim: false, set: 'extra', meme: 'Crying cat thumbs up' },
  { id: 'smudge', label: 'Table cat', anim: false, set: 'extra', meme: 'Smudge the table cat, woman yelling at a cat' },
  { id: 'clueless', label: 'Clueless', anim: false, set: 'extra', meme: 'Clueless, blissfully unaware' },
  { id: 'knife-cat', label: 'Knife cat', anim: false, set: 'extra', meme: 'Cat with a knife' },
  { id: 'nerd', label: 'Um actually', anim: false, set: 'extra', meme: 'Nerd face, um actually' },
  { id: 'moai', label: 'Moai', anim: true, set: 'extra', meme: 'Moai with the vine boom' },
  { id: 'lurk', label: 'Lurk', anim: true, set: 'extra', meme: 'Lurking in chat' },
  { id: 'nod', label: 'Nod', anim: true, set: 'extra', meme: 'Nodders, nodding along' },
  { id: 'doubt', label: 'Doubt', anim: false, set: 'extra', meme: 'Press X to doubt' },
  { id: 'afk', label: 'AFK', anim: true, set: 'extra', meme: 'AFK, away from keyboard' },
  { id: 'lag', label: 'Lag', anim: true, set: 'extra', meme: 'Lag, buffering, high ping' },
  { id: 'salty', label: 'Salty', anim: true, set: 'extra', meme: 'Salty, PJSalt' },
  { id: 'malding', label: 'Malding', anim: true, set: 'extra', meme: 'Malding, mad and balding' },
  { id: 'noted', label: 'Noted', anim: true, set: 'extra', meme: 'NOTED, writing it down' },
  { id: 'touch-grass', label: 'Touch grass', anim: true, set: 'extra', meme: 'Go touch grass' },
  { id: 'party-parrot', label: 'Party parrot', anim: true, set: 'extra', meme: 'Party Parrot' },
  { id: 'pop-cat', label: 'Pop cat', anim: true, set: 'extra', meme: 'Pop Cat' },
  { id: 'cat-box', label: 'Cat box', anim: true, set: 'extra', meme: 'If I fits, I sits' },
  { id: 'bread-cat', label: 'Bread cat', anim: false, set: 'extra', meme: 'Cat breading, face through a bread slice' },
  { id: 'sad-hamster', label: 'Sad hamster', anim: false, set: 'extra', meme: 'Sad hamster with big watery eyes' },
  { id: 'floppa', label: 'Floppa', anim: false, set: 'extra', meme: 'Big Floppa the caracal' },
  { id: 'capybara', label: 'Capybara', anim: false, set: 'extra', meme: 'Ok I pull up, capybara with an orange on its head' },
  { id: 'moo-deng', label: 'Moo Deng', anim: true, set: 'extra', meme: 'Moo Deng, the bouncy baby hippo' },
  { id: 'penguin', label: 'Nihilist penguin', anim: true, set: 'extra', meme: 'Nihilist penguin walking off to the mountains' },
  { id: 'pedro', label: 'Pedro', anim: true, set: 'extra', meme: 'Pedro the dancing raccoon' },
  { id: 'crab-rave', label: 'Crab rave', anim: true, set: 'extra', meme: 'Crab Rave' },
  { id: 'skibidi', label: 'Skibidi', anim: true, set: 'extra', meme: 'Skibidi Toilet' },
  { id: 'chimpanzini', label: 'Chimpanzini', anim: true, set: 'extra', meme: 'Chimpanzini Bananini, Italian brainrot' },
  { id: 'lirili', label: 'Lirili', anim: false, set: 'extra', meme: 'Lirili Larila, cactus elephant in sandals, Italian brainrot' },
  { id: 'assassino', label: 'Cappuccino ninja', anim: true, set: 'extra', meme: 'Cappuccino Assassino, Italian brainrot' },
  { id: 'clanker', label: 'Clanker', anim: true, set: 'extra', meme: 'Clanker, 2025 slang for robots' },
  { id: 'dubai-choc', label: 'Dubai chocolate', anim: false, set: 'extra', meme: 'Dubai chocolate with pistachio filling' },
];
